apiVersion: v1
kind: Secret
metadata:
  name: secret-backend-api
data:
  .dockerconfigjson: eyAJImF1dGhzIjogeyAJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7IAkJCSJhdXRoIjogImRHOWhibXhoTVRNd05qcGtZMnR5WDNCaGRGOHRaMUI2WWkxMWFDMURaWEZZTlVSck1rWnBXWFYzUmpNMlpuTT0iIAkJfSAJfSB9
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: backendport
  labels:
    name: backend
    release: prometheus 
  name: backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: toanla1306/project-3-backend-monitoring:latest
        imagePullPolicy: Always
        ports:
        - name: backendport
          containerPort: 8081
          protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
      - name: secret-backend-api
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer

--- 
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  labels:
    release: prometheus
    app: backend
spec:
  jobLabel: backend
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: backend
      path: /metrics
      interval: 30s