apiVersion: v1
kind: Secret
metadata:
  name: secret-frontend-api
data:
  .dockerconfigjson: eyAJImF1dGhzIjogeyAJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7IAkJCSJhdXRoIjogImRHOWhibXhoTVRNd05qcGtZMnR5WDNCaGRGOHRaMUI2WWkxMWFDMURaWEZZTlVSck1rWnBXWFYzUmpNMlpuTT0iIAkJfSAJfSB9
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: frontendport
  labels:
    name: frontend
    release: prometheus 
  name: frontend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: toanla1306/project-3-frontend-monitoring:latest
        imagePullPolicy: Always
        ports:
        - name: frontendport
          containerPort: 8081
          protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
      - name: secret-frontend-api
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 8081
      targetPort: 8080
  type: LoadBalancer

--- 
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  labels:
    release: prometheus
    app: frontend
spec:
  jobLabel: frontend
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: frontend
      path: /metrics
      interval: 30s