apiVersion: v1
kind: Secret
metadata:
  name: secret-trial-api
data:
  .dockerconfigjson: eyAJImF1dGhzIjogeyAJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7IAkJCSJhdXRoIjogImRHOWhibXhoTVRNd05qcGtZMnR5WDNCaGRGOHRaMUI2WWkxMWFDMURaWEZZTlVSck1rWnBXWFYzUmpNMlpuTT0iIAkJfSAJfSB9
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trialport
  labels:
    name: trial
    release: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
        - name: trial
          image: toanla1306/project-3-trial-monitoring:latest
          imagePullPolicy: Always
          ports:
          - name: trialport
            containerPort: 8080
            protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
      - name: secret-trial-api
---
apiVersion: v1
kind: Service
metadata:
  name: trial
  labels:
    app: trial
spec:
  selector:
    app: trial
  ports:
    - name: trial
      protocol: TCP
      port: 8082
      targetPort: trialport
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trial
  namespace: monitoring
  labels:
    app: trial
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trial
  endpoints:
  - port: trial
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default